In [9]:
import pandas as pd
spain_clean_df = pd.read_csv("results/spain_clean.csv")
team_input = 'FC Barcelona'

team_home_records = spain_clean_df[spain_clean_df['home'] == team_input]
team_visitor_records = spain_clean_df[spain_clean_df['visitor'] == team_input]
team_records_df = [team_home_records, team_visitor_records]
team_records_df = pd.concat(team_records_df).sort_values( by= 'Date')
team_records_df

,Date,Season,home,visitor,score,hgoal,vgoal,hpoint,vpoint
4,1929-02-12,1928,Racing Santander,FC Barcelona,0-2,0,2,0,3
9,1929-02-17,1928,FC Barcelona,Real Madrid,1-2,1,2,0,3
14,1929-02-24,1928,Real Sociedad,FC Barcelona,3-0,3,0,3,0
17,1929-03-03,1928,FC Barcelona,Arenas de Getxo,2-2,2,2,1,1
20,1929-03-10,1928,Atletico Madrid,FC Barcelona,4-1,4,1,3,0
...,...,...,...,...,...,...,...,...,...
26150,2022-05-01,2021,FC Barcelona,RCD Mallorca,2-1,2,1,3,0
26159,2022-05-07,2021,Real Betis,FC Barcelona,1-2,1,2,0,3
26166,2022-05-10,2021,FC Barcelona,Celta Vigo,3-1,3,1,3,0
26178,2022-05-15,2021,Getafe CF,FC Barcelona,0-0,0,0,1,1
26189,2022-05-22,2021,FC Barcelona,Villarreal CF,0-2,0,2,0,3